# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package
on:
  push:
    tags:
      - "*"

jobs:
  - name: Set up Python 3.10
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"
  - uses: actions/checkout@v3
  - name: Install dependencies
    working-directory: .
    run: |
      ls -la
      python -m pip install --upgrade pip
      pip install flake8 pytest
      pip install -r requirements.txt
      pip install -e .
  - name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/fast-checkers
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Publish package distributions to PyPI      
        uses: pypa/gh-action-pypi-publish@release/v1